server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/devkhchua/config.service
          clone-on-start: true